services:
  sylius_dotpay_plugin.bridge.dotpay:
    class: SyliusDotpayPlugin\Bridge\DotpayBridge
    arguments:
      - '%kernel.environment%'
      - '%env(DOTPAY_SANDBOX_HOST)%'
      - '%env(DOTPAY_PRODUCTION_HOST)%'
      - '%env(DOTPAY_SHOP_ID)%'
      - '%env(DOTPAY_SECRET_KEY)%'
      - '%env(DOTPAY_API_VERSION)%'
      - '%env(DOTPAY_BUTTON_TYPE)%'
