services:
  sylius_dotpay_plugin.form.type.dotpay_gateway_configuration:
    class: SyliusDotpayPlugin\Form\Type\DotpayGatewayConfigurationType
    tags:
      - { name: sylius.gateway_configuration_type, type: dotpay, label: sylius_dotpay_plugin.ui.dotpay.dotpay_gateway_label }
      - { name: form.type }
