services:
  sylius_dotpay_plugin.gateway_factory.dotpay:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments:
      -  SyliusDotpayPlugin\DotpayGatewayFactory
    tags:
      - { name: payum.gateway_factory_builder, factory: dotpay }